name: CI/CD on new tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [standard, imperial, r2kt] # <-- Add your environments here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build PlatformIO project for ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}

      - name: Rename and upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: .pio/build/${{ matrix.environment }}/firmware.bin
          
  create_release:
    runs-on: ubuntu-latest
    needs: build_firmware
    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts_dir # All artifacts will be downloaded here

      - name: Upload all firmware files to Release
        run: |
          for file in artifacts_dir/*/*.bin; do
            filename=$(basename "$file")
            asset_name="${filename}" # Rename the file for clarity, if needed
            echo "Uploading asset: $asset_name"
            # The 'upload-release-asset' action is run for each file
            # This requires a new API call for each asset
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "${{ steps.create_release.outputs.upload_url }}?name=${asset_name}" \
            --data-binary "@$file"
          done