name: CI/CD on new tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [standard, imperial, r2kt] # <-- Add your environments here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build PlatformIO project for ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}

      - name: Rename firmware for ${{ matrix.environment }}
        run: mv .pio/build/${{ matrix.environment }}/firmware.bin ${{ matrix.environment }}.bin

      - name: Rename and upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}.bin
          path: ${{ matrix.environment }}.bin
          
  create_release:
    runs-on: ubuntu-latest
    needs: build_firmware
    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts_dir

      - name: List all downloaded files
        run: ls -R artifacts_dir

      - name: Add ${{ matrix.environment }} to release
        uses: xresloader/upload-to-github-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        with:
          file: artifacts_dir/*.bin
