name: CI/CD on new tag

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [standard, imperial, r2kt] # <-- Add your environments here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build PlatformIO project for ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}

      - name: Rename firmware for ${{ matrix.environment }}
        run: mv .pio/build/${{ matrix.environment }}/firmware.bin docs/firmware/${{ matrix.environment }}.bin

      - name: Rename and upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}.bin
          path: docs/firmware/${{ matrix.environment }}.bin


  commit_firmware:
    runs-on: ubuntu-latest
    needs: build_firmware
    permissions:
      contents: write
      
    steps:
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Automated: Upload firmware"
          branch: ${{ github.ref_name }}
          # Path to the files you want to commit.
          # The period means it will commit all changes in the directory
          # You can also specify the exact directory like: 'compiled_binaries'
          file_pattern: docs/firmware/
          
