name: CI/CD on new tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build PlatformIO project
        run: pio run

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/standard/firmware.bin

  create_release:
    runs-on: ubuntu-latest
    needs: build_firmware
    permissions:
      contents: write
      
    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload firmware to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: firmware.bin
          asset_name: firmware.bin
          asset_content_type: application/octet-stream